name: Bandit
on:
  workflow_call:
    inputs:
      bandit-exit-zero:
        description: 'Exit with 0 even if issues are found'
        required: false
        type: boolean
        default: true
      bandit-path:
        description: 'Path to the directory to scan'
        required: false
        type: string
        default: '.'
      bandit-level:
        description: 'Report only issues of a given severity level or higher'
        required: false
        type: string
        default: 'UNDEFINED'
      bandit-confidence:
        description: 'Report only issues of a given confidence level or higher'
        required: false
        type: string
        default: 'UNDEFINED'
      bandit-excluded-paths:
        description: 'Comma-separated list of paths to exclude from scan'
        required: false
        type: string
      bandit-skips:
        description: 'Comma-separated list of test IDs to skip'
        required: false
        type: string
      bandit-ini-path:
        description: 'Path to a .bandit file that supplies command line arguments'
        required: false
        type: string
      
    secrets:
      GITHUB_TOKEN:
        description: 'Token to access the repository'
        required: true
      
jobs:
  bandit:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bandit Scan
        uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
        with: 
          exit_zero: ${{ github.event.inputs.bandit-exit-zero }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.inputs.bandit-path }}
          level: ${{ github.event.inputs.bandit-level }}
          confidence: ${{ github.event.inputs.bandit-confidence }}
          excluded_paths: ${{ github.event.inputs.bandit-excluded-paths }}
          skips: ${{ github.event.inputs.bandit-skips }}
          ini_path: ${{ github.event.inputs.bandit-ini-path }}

