name: devsecops
on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
    workflow_dispatch:
        inputs:
            scan: 
                type: choice
                options:
                - gitleaks
                - safety
                - all
            gitleaks-notify-user-list:
                description: 'List of GitHub accounts that should be alerted when gitleaks-action detects a leak'
                required: false
                type: string
            gitleaks-enable-comments:
                description: 'Boolean value that turns on or off PR commenting'
                required: false
                type: string
            gitleaks-config:
                description: 'Path to a gitleaks configuration file'
                required: false
                type: string
            gitleaks-enable-upload-artifact:
                description: 'Boolean value that turns on or off uploading a sarif artifact when gitleaks detects secrets'
                required: false
                type: string
            gitleaks-enable-summary:
                description: 'Boolean value to enable or disable gitleaks job summary'
                required: false
                type: string
            gitleaks-version:
                description: 'A particular Gitleaks version to use (e.g. 8.15.3, no v prefix) or use latest to always use the newest available version'
                required: false
                type: string
            safety-args:
                description: 'Any additional arguments to pass to Safety'
                required: false
                default: ''
                type: string

jobs:
    secrets:
        if: (github.events.choice == 'gitleaks' || github.events.choice == 'all' ) || github.event_name == 'push' || github.event_name == 'pull_request'
        uses: ./.github/workflows/gitleaks.yml
        with:
            gitleaks-notify-user-list: ${{ github.event.inputs.gitleaks-notify-user-list }}
            gitleaks-enable-comments: ${{ github.event.inputs.gitleaks-enable-comments || 'true' }}
            gitleaks-config: ${{ github.event.inputs.gitleaks-config }}
            gitleaks-enable-upload-artifact: ${{ github.event.inputs.gitleaks-enable-upload-artifact }}
            gitleaks-enable-summary: ${{ github.event.inputs.gitleaks-enable-summary || 'true' }}
            gitleaks-version: ${{ github.event.inputs.gitleaks-version }}
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
    sca:
        if: (github.events.choice == 'safety' || github.events.choice == 'all' ) || github.event_name == 'push' || github.event_name == 'pull_request'
        uses: ./.github/workflows/safety.yml
        with:
            args: ${{ github.event.inputs.args }}
        secrets:
            api-key: ${{ secrets.SAFETY_API_KEY }}
    sast:
        if: (github.events.choice == 'bandit' || github.events.choice == 'all' ) || github.event_name == 'push' || github.event_name == 'pull_request'
        uses: ./.github/workflows/bandit.yml
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
    