name: GitLeaks

on:
    workflow_call:
        inputs:
            gitleaks-notify-user-list:
                description: 'List of GitHub accounts that should be alerted when gitleaks-action detects a leak'
                required: false
                type: string
            gitleaks-enable-comments:
                description: 'Boolean value that turns on or off PR commenting'
                required: false
                type: string
            gitleaks-config:
                description: 'Path to a gitleaks configuration file'
                required: false
                type: string
            gitleaks-enable-upload-artifact:
                description: 'Boolean value that turns on or off uploading a sarif artifact when gitleaks detects secrets'
                required: false
                type: string
            gitleaks-enable-summary:
                description: 'Boolean value to enable or disable gitleaks job summary'
                required: false
                type: string
            gitleaks-version:
                description: 'A particular Gitleaks version to use (e.g. 8.15.3, no v prefix) or use latest to always use the newest available version'
                required: false
                type: string

        secrets:
            token:
                description: 'Token to access the repository'
                required: true
            gitleaks-license:
                description: 'License for gitleaks'
                required: false
            
                
    
jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: grisolfi/gitleaks-action@1053e958940d09d4974da93bf31c7b29266af53b
              env:
                GITHUB_TOKEN: ${{ secrets.token }}
                GITLEAKS_LICENSE: ${{ secrets.gitleaks-license }}
                GITLEAKS_NOTIFY_USER_LIST: ${{ github.event.inputs.gitleaks-notify-user-list }}
                GITLEAKS_ENABLE_COMMENTS: ${{ github.event.inputs.gitleaks-enable-comments }}
                GITLEAKS_CONFIG: ${{ github.event.inputs.gitleaks-config }}
                GITLEAKS_ENABLE_UPLOAD_ARTIFACT: ${{ github.event.inputs.gitleaks-enable-upload-artifact }}
                GITLEAKS_ENABLE_SUMMARY: ${{ github.event.inputs.gitleaks-enable-summary }}
                GITLEAKS_VERSION: ${{ github.event.inputs.gitleaks-version }}
