name: Zap

on:
    workflow_call:

permissions:
    issues: write
    packages: read
jobs:
    zap:
        services:
            vampi:
                image: ghcr.io/ghcr.io/molocohrrr/vampi:ci
                credentials:
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                ports:
                    - 5000:5000
        runs-on: ubuntu-latest
        steps:
            - name: Zap Baseline
              uses: zaproxy/action-baseline@f00f834c0f443c58e7edd33d973f33305370dacf
              with:
                target: http://localhost:5000
                allow_issue_writing: true